spring:
  kafka:
    bootstrap-servers: ${TC_KAFKA}
    consumer:
      auto-offset-reset: earliest
      group-id: demo
      properties:
        heartbeat.interval.ms: 1000
        session.timeout.ms: 1500
